version: '2'
services:
  mysql:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    hostname: 'mysql'
    environment:
      MYSQL_DATABASE: 'slidehub'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: 'dockerfile_dev'
    depends_on:
      - mysql
    environment:
      RAILS_ENV: development
      OSS_BUCKET_NAME: $OSS_BUCKET_NAME
      OSS_IMAGE_BUCKET_NAME: $OSS_IMAGE_BUCKET_NAME
      OSS_USE_S3_STATIC_HOSTING: $OSS_USE_S3_STATIC_HOSTING
      OSS_REGION: $OSS_REGION
      OSS_CDN_BASE_URL: $OSS_CDN_BASE_URL
      OSS_SQS_URL: $OSS_SQS_URL
      OSS_AWS_ACCESS_ID: $OSS_AWS_ACCESS_ID
      OSS_AWS_SECRET_KEY: $OSS_AWS_SECRET_KEY
      OSS_DB_NAME_DEV: 'slidehub'
      OSS_DB_USERNAME_DEV: 'root'
      OSS_DB_PASSWORD_DEV: 'pass'
      OSS_DB_URL_DEV: 'mysql'
      OSS_DB_NAME_TEST: 'test_slidehub'
      OSS_DB_USERNAME_TEST: 'root'
      OSS_DB_PASSWORD_TEST: 'pass'
      OSS_DB_URL_TEST: 'mysql'
      OSS_FACEBOOK_APP_ID: $OSS_FACEBOOK_APP_ID
      OSS_FACEBOOK_APP_SECRET: $OSS_FACEBOOK_APP_SECRET
      OSS_TWITTER_CONSUMER_KEY: $OSS_TWITTER_CONSUMER_KEY
      OSS_TWITTER_CONSUMER_SECRET: $OSS_TWITTER_CONSUMER_SECRET
      OSS_TWITTER_CALLBACK_URL: 'http://localhost:3000/users/auth/twitter/callback'
      OSS_FROM_EMAIL: test@example.com
      OSS_SMTP_SERVER: localhost
      OSS_SMTP_PORT: 1025
      OSS_SMTP_AUTH_METHOD: plain
      OSS_SMTP_PASSWORD: test
      OSS_SMTP_USERNAME: test
      RAILS_LOG_TO_STDOUT: 'yes'
    ports:
      - '3000:3000'
      - '1080:1080'
    volumes:
      - .:/opt/application/current:cached

volumes:
  mysql-data:
    driver: local
